### ISSUE TITLE
Error Fatal / nvm

### ISSUE THREAD

**Issue by Fengxiah** [neowutran/ShinraMeter#376] opened 2017-08-24 16:57 UTC
Hi, 
I can't seem to make the meter work ever since this afternoon, can u help me ? here's my log : 

Edit : i didnt know it was the same for everyone/

**Comment by clfarron4** [comment] 2017-08-24 17:01
We know it doesn't work. Patches have been implemented so it doesn't work.

Possible duplicate of https://github.com/neowutran/ShinraMeter/issues/375

**Comment by Fengxiah** [comment] 2017-08-24 17:32
Oh mb I didnt know

**Closed** 2017-09-09 07:16 UTC
Labels: help needed, request
