### ISSUE TITLE
Weird crashing issue?

### ISSUE THREAD

**Issue by Sirachasauce** [neowutran/ShinraMeter#210] opened 2016-10-03 02:54 UTC
I was on 1.44 and it was working perfectly fine and once I updated to the newest shinra, my meter wont show the next fight's stats. It will just stay on the previous one and when I hit delete, nothing will show up and it forces me to restart the meter and game and after a fight or two, itll just stop working again. So I was forced to go back on 1.44 and everything was fine. Not sure why this is happening. If I stay on 1.44 will it still export dfh/nm, ssh/nm, mm, etc?

**Comment by Gl0** [comment] 2016-10-03 07:07
Only SSHM, other was added later.
Anything in error log? Have you tried to disable chat and notification services?

**Comment by Sirachasauce** [comment] 2016-10-03 11:48
No I have not because the chat was already implemented in 1.44, but i will try to disable it.

**Comment by Gl0** [comment] 2016-10-03 15:35
There were a lot of additions to this services after 1.44.
But error.log is still interesting to see.

**Comment by Sirachasauce** [comment] 2016-10-04 00:00
Ok I disabled the notifications, and it seems to be working fine for the moment. If it happens again, I will post the error log (unintalled the more recent version for the 1.44 so I lost the log, sorry.)

**Comment by ve3k** [comment] 2016-10-04 08:06
I have the same issue. After latest update meter keeps disconnecting all the time and wont read anymore date. I've tried to disable notifications and chat and several config adjustments but with no effect on the issue.
Error log have something like this after every disconnect:
2016-10-03 19:03:49,011 [42] ERROR ShinraMeter [(null)] - ##### (version=1.48):
##### Debug: Low priority Received: 8293027
8293365: 28
8293393: 91
8293484: 14
8293498: 16
8293514: 16
8293530: 44
8293574: 12
8293586: 36
8293622: 88
8293710: 16
Queue length:1001
New Queue length:1001
2016-10-03 19:23:23,913 [35] ERROR ShinraMeter [(null)] - ##### (version=1.48):
##### Debug: Low priority Received: 11728519
11728563: 44
11728607: 21
11728628: 21
11728649: 32
11728681: 44
11728725: 44
11728769: 44
11728813: 64
11728877: 16
11728893: 64
Queue length:1001
New Queue length:1001

**Comment by Gl0** [comment] 2016-10-04 13:02
Such debugs have nothing related to anything added in 1.44+, that means that meter have lost some packets due to some driver or CPU overload issue. Each entry - is "unfreezing" workaround, forcing meter to stop waiting for missed packets and try to parse all other in queue. There can be a lot of time elapsed before it triggers (1000 packets in queue), but if missed packets were not critical and there are no other missed packets - meter should continue counting. But anyway, if such debug appear in log - something wrong with your computer, meter can receive data that is not valid (missed packets were probably skipped because of bad structure) and make it crash.
Probably we'll decrease number of packets in queue to wait before considering missed packets as missed, but not sure, which number is enough to eliminate false triggering on reordered/retransmitted packets.

**Comment by ve3k** [comment] 2016-10-04 13:13
I'll monitor my PC performance closely and let you know how it goes. 
But before last update i didn't experience this problem. Started just with the last update and i didn't change anything.

**Comment by Cupcakes123** [comment] 2016-10-05 00:43
Nevermind, spoke too soon. It started to not disconnect/not register the next fight anymore.

2016-10-04 02:49:40,257 [5] ERROR ShinraMeter [(null)] - ##### (version=1.48):
##### CRASH #####
Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at NetworkSniffer.TcpConnection.HandleTcpReceived(UInt32 sequenceNumber, ArraySegment`1 data)
   at NetworkSniffer.TcpSniffer.Receive(ArraySegment`1 ipData)
   at NetworkSniffer.IpSniffer.OnPacketReceived(ArraySegment`1 data)
   at NetworkSniffer.IpSniffer.OnPacketReceived(ArraySegment`1 data)
   at NetworkSniffer.IpSnifferRawSocketSingleInterface.Receive(IAsyncResult ar)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.CompleteCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
System.Core
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at NetworkSniffer.TcpConnection.HandleTcpReceived(UInt32 sequenceNumber, ArraySegment`1 data)
   at NetworkSniffer.TcpSniffer.Receive(ArraySegment`1 ipData)
   at NetworkSniffer.IpSniffer.OnPacketReceived(ArraySegment`1 data)
   at NetworkSniffer.IpSniffer.OnPacketReceived(ArraySegment`1 data)
   at NetworkSniffer.IpSnifferRawSocketSingleInterface.Receive(IAsyncResult ar)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.CompleteCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
System.Collections.ListDictionaryInternal

TSource First[TSource](System.Collections.Generic.IEnumerable`1[TSource])
2016-10-04 02:59:29,587 [9] ERROR ShinraMeter [(null)] - ##### (version=1.48):
##### CRASH #####
Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at NetworkSniffer.TcpConnection.HandleTcpReceived(UInt32 sequenceNumber, ArraySegment`1 data)
   at NetworkSniffer.TcpSniffer.Receive(ArraySegment`1 ipData)
   at NetworkSniffer.IpSniffer.OnPacketReceived(ArraySegment`1 data)
   at NetworkSniffer.IpSniffer.OnPacketReceived(ArraySegment`1 data)
   at NetworkSniffer.IpSnifferRawSocketSingleInterface.Receive(IAsyncResult ar)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.CompleteCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
System.Core
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at NetworkSniffer.TcpConnection.HandleTcpReceived(UInt32 sequenceNumber, ArraySegment`1 data)
   at NetworkSniffer.TcpSniffer.Receive(ArraySegment`1 ipData)
   at NetworkSniffer.IpSniffer.OnPacketReceived(ArraySegment`1 data)
   at NetworkSniffer.IpSniffer.OnPacketReceived(ArraySegment`1 data)
   at NetworkSniffer.IpSnifferRawSocketSingleInterface.Receive(IAsyncResult ar)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.CompleteCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
System.Collections.ListDictionaryInternal

Im confused to why it will work on 1.44 perfectly and not the most recent update.

**Comment by Sirachasauce** [comment] 2016-10-05 00:49
Nevermind, spoke too soon. It started to not disconnect/not register the next fight anymore.

2016-10-04 02:49:40,257 [5] ERROR ShinraMeter [(null)] - ##### (version=1.48):

CRASH

Sequence contains no elements
at System.Linq.Enumerable.FirstTSource
at NetworkSniffer.TcpConnection.HandleTcpReceived(UInt32 sequenceNumber, ArraySegment1 data) at NetworkSniffer.TcpSniffer.Receive(ArraySegment1 ipData)
at NetworkSniffer.IpSniffer.OnPacketReceived(ArraySegment1 data) at NetworkSniffer.IpSniffer.OnPacketReceived(ArraySegment1 data)
at NetworkSniffer.IpSnifferRawSocketSingleInterface.Receive(IAsyncResult ar)
at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
at System.Net.ContextAwareResult.CompleteCallback(Object state)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Net.ContextAwareResult.Complete(IntPtr userToken)
at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
System.Core
System.InvalidOperationException: Sequence contains no elements
at System.Linq.Enumerable.FirstTSource
at NetworkSniffer.TcpConnection.HandleTcpReceived(UInt32 sequenceNumber, ArraySegment1 data) at NetworkSniffer.TcpSniffer.Receive(ArraySegment1 ipData)
at NetworkSniffer.IpSniffer.OnPacketReceived(ArraySegment1 data) at NetworkSniffer.IpSniffer.OnPacketReceived(ArraySegment1 data)
at NetworkSniffer.IpSnifferRawSocketSingleInterface.Receive(IAsyncResult ar)
at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
at System.Net.ContextAwareResult.CompleteCallback(Object state)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Net.ContextAwareResult.Complete(IntPtr userToken)
at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
System.Collections.ListDictionaryInternal

TSource FirstTSource
2016-10-04 02:59:29,587 [9] ERROR ShinraMeter [(null)] - ##### (version=1.48):

CRASH

Sequence contains no elements
at System.Linq.Enumerable.FirstTSource
at NetworkSniffer.TcpConnection.HandleTcpReceived(UInt32 sequenceNumber, ArraySegment1 data) at NetworkSniffer.TcpSniffer.Receive(ArraySegment1 ipData)
at NetworkSniffer.IpSniffer.OnPacketReceived(ArraySegment1 data) at NetworkSniffer.IpSniffer.OnPacketReceived(ArraySegment1 data)
at NetworkSniffer.IpSnifferRawSocketSingleInterface.Receive(IAsyncResult ar)
at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
at System.Net.ContextAwareResult.CompleteCallback(Object state)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Net.ContextAwareResult.Complete(IntPtr userToken)
at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
System.Core
System.InvalidOperationException: Sequence contains no elements
at System.Linq.Enumerable.FirstTSource
at NetworkSniffer.TcpConnection.HandleTcpReceived(UInt32 sequenceNumber, ArraySegment1 data) at NetworkSniffer.TcpSniffer.Receive(ArraySegment1 ipData)
at NetworkSniffer.IpSniffer.OnPacketReceived(ArraySegment1 data) at NetworkSniffer.IpSniffer.OnPacketReceived(ArraySegment1 data)
at NetworkSniffer.IpSnifferRawSocketSingleInterface.Receive(IAsyncResult ar)
at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
at System.Net.ContextAwareResult.CompleteCallback(Object state)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Net.ContextAwareResult.Complete(IntPtr userToken)
at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
System.Collections.ListDictionaryInternal

Im confused to why it will work on 1.44 perfectly and not the most recent update.

**Comment by Gl0** [comment] 2016-10-05 01:21
I've seen such error in debug.log even on 1.33. That one says that mentioned workaround skipped all 1000 packets in queue, but didn't find any one small enough to start parsing with. Not sure, how that's possible. Can't reproduce it. It's rare enough, less than 1% of our users have this issue. And yes, number of users with this problem started to grow last week. May be windows updated some network card drivers to bad version?

**Comment by Sirachasauce** [comment] 2016-10-05 01:33
I updated everything I could, but nothing helped for me at least D=
Ill probably go back to 1.44 for now and hopefully this can be fixed somehow later^^

**Comment by Gl0** [comment] 2016-10-05 04:53
btw, have you tried changing meter priority via   `<low_priority>false</low_priority>` in window.xml ?

**Comment by Sirachasauce** [comment] 2016-10-05 04:59
yes I have, I even tried to change the priority on my network for shinra, but still doesnt work.

**Comment by Gl0** [comment] 2016-10-05 05:04
we'll probably try to add another buffer to store raw captured data before all checks and decryption, may be it helps.

**Comment by Gl0** [comment] 2016-10-06 01:54
Previous workaround was not working. In next version there will be working one.
+ Optimized raw sockets.
Hope that would help a bit with this issue.
But anyway, don't know what you are doing with your computers that they start to miss packets. When debugging the workaround I had to stop capturing thread for more than minute so that it start missing.
If you are using raw sockets - it's a good idea to stop any background network transfer, cause meter have to take all traffic from kernel level to userspace to filter out game traffic from the trash.
Anyway, it's a good idea to stop network intense applications when playing MMO, even without meter.=)

**Comment by ve3k** [comment] 2016-10-07 07:08
So after more thorough investigation. Spotify web player is what kills the traffic to Shinrameter. I can stream, talk on voice, donwload torrents and all is working fine. When i just play tera with meter and start spotify web player. After a minute or two meter stops with error.

**Comment by Gl0** [comment] 2016-10-07 12:13
If you are using raw sockets mode - issue with crashing on bad localhost traffic is fixed in 1.49

**Comment by Sirachasauce** [comment] 2016-10-08 11:29
so far the new update has been working very well, ty for the fix!

**Closed** 2016-10-17 08:25 UTC
