### ISSUE TITLE
[POPUP NOTIFICATION] click throu needed

### ISSUE THREAD

**Issue by dovev1** [neowutran/ShinraMeter#335] opened 2017-05-20 16:55 UTC
posted the "question" few days ago about mouse being stuck(left right click), and found out why (even on click tru), since elite bar is usualy down right, and if you click nostrum pot and instantly start moving, mouse is left in that corner, where usualy msgs like enrage, missing nostrum etc, happen (all from SHINRA METERS SIDE), and if you click while msgs pop, it gets stuck untill msg is gone. so there you have it, dissing out an issue just cuz you are bored or lazy to investigate. smh

**Comment by neowutran** [comment] 2017-05-20 17:16
The click throu option doesn't work on the notification window due to a limitation of the library used for it (NotifyIcon.Wpf). 
To allow click thou on the notification window + repositionning -> need a complete rewrite of the notification UI system & to remove dependency to NotifyIcon.Wpf  

No quick fix for that, except disabling every notification popup if it s too annoying for you (you can replace the popup notification  by a text-to-speech notification, should be conveniant enough )
 
& ya, if not enought details to reproduce the issue, I close the issue, not enough ppl to investigate on the issues of everyone

**Comment by neowutran** [comment] 2017-05-20 17:23
#328 #283 #275

**Comment by neowutran** [comment] 2017-05-20 18:50
a fix will be released in 1.97, if you know how to compile you can try it yourself now

**Comment by neowutran** [comment] 2017-05-25 06:50
1.97 released, should be fixed

**Closed by neowutran** 2017-05-25 06:50 UTC
Labels: Question, request
